version: '3'

services:
  flowers:
    image: tensorflow/serving
    deploy:
      replicas: 5
    ports:
      - 9500:8500
      - 9501:8501
    volumes:
      - ${MODELS}:/models/flowers
    environment:
      - MODEL_NAME=flowers

  visualizer:
    image: dockersamples/visualizer
    deploy:
      placement:
        constraints: [node.role == manager]
    ports:
      - 9001:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
